//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kriteek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friendship
    {
        public long PersonID { get; set; }
        public long FriendID { get; set; }
        public long Type { get; set; }
    
        public virtual Person person { get; set; }
        public virtual Friendtype friendtype { get; set; }
        public virtual Person person1 { get; set; }
    }
}
