//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kriteek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friendtype
    {
        public Friendtype()
        {
            this.friendships = new HashSet<Friendship>();
            this.posts = new HashSet<Post>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Friendship> friendships { get; set; }
        public virtual ICollection<Post> posts { get; set; }
    }
}
