//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kriteek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friendtype
    {
        public Friendtype()
        {
            this.Members = new HashSet<Person>();
            this.CanSee = new HashSet<Post>();
        }
    
        public int PosterID { get; set; }
        public string Type { get; set; }
    
        public virtual Person Poster { get; set; }
        public virtual ICollection<Person> Members { get; set; }
        public virtual ICollection<Post> CanSee { get; set; }
    }
}
