//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kriteek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.friendships = new HashSet<Friendship>();
            this.friendships1 = new HashSet<Friendship>();
            this.ratings = new HashSet<Rating>();
        }
    
        public long ID { get; set; }
        public string First { get; set; }
        public string Last { get; set; }
    
        public virtual ICollection<Friendship> friendships { get; set; }
        public virtual ICollection<Friendship> friendships1 { get; set; }
        public virtual ICollection<Rating> ratings { get; set; }
    }
}
