//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kriteek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Friendtypes = new HashSet<Friendtype>();
            this.Posts = new HashSet<Post>();
            this.Ratings = new HashSet<Rating>();
            this.Friends = new HashSet<Friendtype>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public string First { get; set; }
        public string Last { get; set; }
    
        public virtual ICollection<Friendtype> Friendtypes { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<Friendtype> Friends { get; set; }
    }
}
