//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kriteek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.ratings = new HashSet<Rating>();
            this.topics = new HashSet<topic>();
            this.friendtypes = new HashSet<Friendtype>();
        }
    
        public long ID { get; set; }
        public int Type { get; set; }
        public string Content { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual ICollection<Rating> ratings { get; set; }
        public virtual ICollection<topic> topics { get; set; }
        public virtual ICollection<Friendtype> friendtypes { get; set; }
    }
}
