//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kriteek.Models
{
    using System;
    
    public enum PostRating : int
    {
        Strongly_Dislike = 0,
        Dislike = 1,
        Neutral = 3,
        Like = 4,
        Strongly_Like = 5
    }
}
