//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kriteek.Models
{
    using System;
    
    public enum RatingValue : int
    {
        Strongly_Dislike = -2,
        Dislike = -1,
        Neutral = 0,
        Like = 1,
        Stringly_Like = 2
    }
}
