//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kriteek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public long PersonID { get; set; }
        public long PostID { get; set; }
        public RatingValue RatingValue { get; set; }
    
        public virtual Person person { get; set; }
        public virtual Post post { get; set; }
    }
}
