//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kriteek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int RaterID { get; set; }
        public int PostID { get; set; }
        public PostRating Value { get; set; }
    
        public virtual Person Rater { get; set; }
        public virtual Post Post { get; set; }
    }
}
